name: Test YAML Files

on:
  push:
    branches:
      - test
    paths:
      - '**/*.yaml'

jobs:
  test_yaml_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 

    - name: Download USPAgent
      run: sudo python3 USPython.py -d

    - name: Run USPython.py command
      run: |
        for file in $(git diff --name-only HEAD^ HEAD | grep '.yaml'); do
          sudo python3 USPython.py -m command -f $file
        done

    - name: Fail the push
      if: always()
      run: |
        echo "[+] Works"
        exit 0