name: Setup Environment and Run Script

on:
  push:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: Install Git
      run: |
        sudo apt-get install -y git

    - name: Run USPython.py script
      run: |
        sudo python3 USPython.py
